### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by coderofsalvation** [maks/elfer#8]
first of all, awesome project.
It kind of unites the polyend tracker-concept with the electribe.
Also, elfer is interesting as it does not depend on hacktribe (but is compatible with).
I suspect that only 1% of the technical electribe  owners is going to risk flashing their device with experimental firmware.
In that sense, the empowering factor of elfer is much bigger.
Let me highlight my personal favorites:

> export/import other file formats, eg. Sunvox

How about just import/export a midi file? Its the gold standard which most daw's and trackers can import/export (including sunvox), and is probably easier than generating some kind of daw-specific fileformat.
This would be so awesome because one could edit/tweak/backup patterns and collaborate/remix patterns (with people without electribe).
On top of that, it would allow a daw-to-electribe workflow: build a nice pattern/eq'ed mix in sunvox, and then in sunvox export the midifile + one sample with all used samples.
(samples are retargeted by osc edit on electribe)
I already do this (by loading the sample from SD), but it would be nice if the midifile could also be uploaded (thru elfer).

> sample editor

launching a (configurable) '/usr/bin/audacity "%s"'  systemcall would suffice for me (a diy sample editor can be quite a rabbithole).

> (idea) midi cc macros / piggybacking

lets say my drums are on tracks 1,2,3 it would be nice if we could 'couple' certain params (group params).
Possible UX: select some tracks (1,2,3 e.g.) then select a param (volume)..it will read out the current volume-values (70,90,100), basically the preferred maximums..then if you change the volume-knob of one of those tracks, elfer will automatically affect all selected track-volumes (1,2,3) basically interpolating between 0 and the preferred maximums (70,90,100).
If you could add many macros you could literally create complete songs out of one pattern by just dialing some macro knobs..
To be fair, this might be a bit out of scope as it is more a midicontroller nicetohave.

anyways just my few cents, I love your work!

> ps. are there binaries to test?

**Comment by maks** [comment]
@coderofsalvation thank you very much! I'm glad you like it. 
Unfortunately I've decided not to pursue the project further and I no longer have an E2, so I'll shortly mark the repo as archived, though I would be **very** happy for anyone to fork it and continue developing it further. 
For myself, I'll likely reuse some parts of it on other music app projects I have planned, but in the end I decided that the workflow with the E2, even enhanced with hacktribe and Elfer didn't really suit what I wanted to do.
